import React from 'react';
import { 
  TrendingUp, 
  User, 
  ShieldHalf, 
  Variable, 
  Triangle, 
  Building2, 
  Hammer, 
  Droplets, 
  Square, 
  Paintbrush, 
  FlaskConical, 
  Calendar, 
  Car, 
  HeartPulse, 
  Stethoscope, 
  Sword, 
  ArrowLeftRight, 
  Briefcase, 
  Tags, 
  Settings, 
  Trophy, 
  Leaf, 
  ChefHat, 
  GraduationCap, 
  Dices, 
  Cpu, 
  Heart, 
  Dna, 
  Footprints, 
  Sprout, 
  Clock, 
  Globe, 
  Shirt, 
  Beaker, 
  Film, 
  Brain, 
  Gamepad2, 
  Baby, 
  Scale, 
  Coins, 
  Laptop, 
  Zap, 
  Truck, 
  Wifi, 
  Telescope, 
  Plane, 
  Tent,
  Calculator,
  Aperture,
  Microscope,
  Music,
  Map,
  Compass,
  Anchor,
  Flame,
  Binary,
  CloudRain,
  Factory,
  Pill,
  Fingerprint,
  Mic2,
  Package,
  Activity
} from 'lucide-react';

export const CATEGORY_ICON_MAP: Record<string, React.ReactNode> = {
  'finance': <TrendingUp />,
  'personal': <User />,
  'insurance': <ShieldHalf />,
  'math': <Variable />,
  'roofing': <Triangle />,
  'real-estate': <Building2 />,
  'construction': <Hammer />,
  'hydraulics': <Droplets />,
  'masonry': <Square />,
  'home-improvement': <Paintbrush />,
  'science': <FlaskConical />,
  'everyday': <Calendar />,
  'automotive': <Car />,
  'health': <HeartPulse />,
  'medical': <Stethoscope />,
  'military': <Sword />,
  'converters': <ArrowLeftRight />,
  'business': <Briefcase />,
  'sales': <Tags />,
  'engineering': <Settings />,
  'sports': <Trophy />,
  'environment': <Leaf />,
  'culinary': <ChefHat />,
  'academic': <GraduationCap />,
  'hobbies': <Dices />,
  'tech': <Cpu />,
  'lifestyle': <Heart />,
  'biology': <Dna />,
  'pets': <Footprints />,
  'gardening': <Sprout />,
  'time-date': <Clock />,
  'geography': <Globe />,
  'fashion': <Shirt />,
  'chemistry': <Beaker />,
  'entertainment': <Film />,
  'mental-health': <Brain />,
  'gaming': <Gamepad2 />,
  'parenting': <Baby />,
  'legal': <Scale />,
  'crypto': <Coins />,
  'freelance': <Laptop />,
  'self-improvement': <Zap />,
  'logistics': <Truck />,
  'home-tech': <Wifi />,
  'space': <Telescope />,
  'intl-travel': <Plane />,
  'survival-bushcraft': <Tent />,
  'creative-arts': <Aperture />,
  'marine-science': <Anchor />,
  'data-science': <Binary />,
  'cyber-sec': <Fingerprint />,
  'geology': <Map />,
  'weather-pro': <CloudRain />,
  'retail-pro': <Package />,
  'manufacturing': <Factory />,
  'music-theory': <Music />,
  'audio-pro': <Mic2 />,
  'pharmacy': <Pill />,
  'disaster-prep': <Flame />,
  'pet-wellness': <Activity />
};

export const getCategoryIcon = (slug: string, className: string = "w-5 h-5") => {
  const icon = CATEGORY_ICON_MAP[slug] || <Calculator />;
  return React.cloneElement(icon as React.ReactElement<any>, { className });
};
