export interface CalculatorItem {
  name: string;
  path: string;
  desc: string;
}

export interface CategoryData {
  title: string;
  slug: string;
  description: string;
  items: CalculatorItem[];
}

export const CATEGORIES: CategoryData[] = [
  {
    title: 'Finance & Investment',
    slug: 'finance',
    description: 'Grow your wealth and manage your debt with precision. Our finance suite covers everything from daily budgeting to complex investment analysis and tax planning.',
    items: [
      { name: '12-Hour Shift Pay Calculator', path: '/12-hour-shift-pay', desc: 'Calculate earnings for 12-hour shift rotations.' },
      { name: '3x Rent Calculator', path: '/3x-rent-calculator', desc: 'Check if your income meets the 3x rent rule.' },
      { name: '401k Calculator', path: '/401k', desc: 'Estimate future 401k balance.' },
      { name: 'Adjusted Gross Income', path: '/agi-calculator', desc: 'Calculate your AGI for tax purposes.' },
      { name: 'ADR Calculator', path: '/adr-calculator', desc: 'Average Daily Rate for hospitality management.' },
      { name: 'AFFO Calculator', path: '/affo-calculator', desc: 'Adjusted Funds From Operations for REITs.' },
      { name: 'Alabama Tax Calculator', path: '/alabama-tax', desc: 'Estimate Alabama state income tax.' },
      { name: 'AMT Calculator', path: '/amt-calculator', desc: 'Alternative Minimum Tax calculation.' },
      { name: 'Annual Income Calculator', path: '/annual-income', desc: 'Calculate total yearly earnings.' },
      { name: 'Annual Income Quiz', path: '/annual-income-quiz', desc: 'Test your knowledge of income metrics.' },
      { name: 'Annuity Calculator', path: '/annuity', desc: 'Analyze traditional annuity growth.' },
      { name: 'Annuity Payout', path: '/annuity-payout', desc: 'Calculate regular income streams.' },
      { name: 'ARM Mortgage Calculator', path: '/arm-mortgage', desc: 'Adjustable Rate Mortgage payment analysis.' },
      { name: 'ARV Calculator', path: '/arv-calculator', desc: 'After Repair Value for property flips.' },
      { name: 'Auto Lease Calculator', path: '/auto-lease', desc: 'Compare monthly leasing costs.' },
      { name: 'Auto Loan Calculator', path: '/auto-loan', desc: 'Plan your vehicle purchase payments.' },
      { name: 'Average Return', path: '/average-return', desc: 'Calculate geometric mean of returns.' },
      { name: 'Biden Tax Plan Calculator', path: '/biden-tax-plan', desc: 'Analyze impact of proposed tax changes.' },
      { name: 'Bill Rate Calculator', path: '/bill-rate', desc: 'Calculate optimal hourly billing rates.' },
      { name: 'Billable Hours Calculator', path: '/billable-hours', desc: 'Track time and calculate client billing.' },
      { name: 'Biweekly Mortgage Calculator', path: '/bi-weekly-mortgage-payment', desc: 'Detailed breakdown of bi-weekly savings.' },
      { name: 'Boat Loan Calculator', path: '/boat-loan', desc: 'Finance your nautical adventures.' },
      { name: 'Bond Calculator', path: '/bond', desc: 'Calculate yield and maturity of bonds.' },
      { name: 'Budget Calculator', path: '/budget', desc: 'Organize your monthly spending.' },
      { name: 'Build Back Better Calculator', path: '/build-back-better-tax', desc: 'Estimate impact of the BBB Act provisions.' },
      { name: 'Business Loan Calculator', path: '/business-loan', desc: 'Analyze commercial financing costs.' },
      { name: 'California Sales Tax Calculator', path: '/california-sales-tax', desc: 'Calculate CA sales tax by location.' },
      { name: 'California Tax Calculator', path: '/california-tax', desc: 'Estimate CA state income tax liability.' },
      { name: 'Cap Rate Calculator', path: '/cap-rate', desc: 'Capitalization Rate for real estate investments.' },
      { name: 'Capital Gains Tax', path: '/capital-gains-tax', desc: 'Calculate tax on investment profits.' },
      { name: 'Capital Gains Tax UK', path: '/capital-gains-tax-uk', desc: 'Calculate UK specific capital gains tax and allowances.' },
      { name: 'CD Calculator', path: '/cd', desc: 'Certificate of Deposit earnings.' },
      { name: 'College Cost Calculator', path: '/college-cost', desc: 'Estimate future tuition and expenses.' },
      { name: 'Commercial Lease Calculator', path: '/commercial-lease', desc: 'Analyze commercial rental agreements.' },
      { name: 'Commission Calculator', path: '/commission', desc: 'Calculate sales rep earnings.' },
      { name: 'Compound Interest', path: '/compound-interest', desc: 'Calculate investment growth over time.' },
      { name: 'Credit Card Payoff', path: '/credit-card', desc: 'Plan your debt payoff strategy.' },
      { name: 'Cryptocurrency', path: '/crypto', desc: 'Track gains across digital assets.' },
      { name: 'Debt Consolidation', path: '/debt-consolidation', desc: 'Analyze if combining loans saves money.' },
      { name: 'Debt Payoff Calculator', path: '/debt-payoff', desc: 'Strategize your exit from debt.' },
      { name: 'Depreciation Calculator', path: '/depreciation', desc: 'Calculate asset value loss over time.' },
      { name: 'Dividend Calculator', path: '/dividend', desc: 'Estimate regular income from stocks.' },
      { name: 'Down Payment Calculator', path: '/down-payment', desc: 'Calculate required home purchase deposit.' },
      { name: 'Earnest Money Calculator', path: '/earnest-money', desc: 'Estimate good-faith deposit for home offers.' },
      { name: 'Estate Tax Calculator', path: '/estate-tax', desc: 'Plan for inheritance and estate transfers.' },
      { name: 'FHA Loan Calculator', path: '/fha-loan', desc: 'Analyze Federal Housing Administration loans.' },
      { name: 'FICA Tax Calculator', path: '/fica-tax', desc: 'Calculate Social Security and Medicare withholdings.' },
      { name: 'Florida Sales Tax Calculator', path: '/florida-sales-tax', desc: 'Calculate FL sales tax including local surtax.' },
      { name: 'Future Value', path: '/future-value', desc: 'Calculate future wealth from principal.' },
      { name: 'Gift of Equity Calculator', path: '/gift-of-equity', desc: 'Calculate tax and equity for family sales.' },
      { name: 'Gross Rent Multiplier', path: '/grm-calculator', desc: 'GRM for income property valuation.' },
      { name: 'Gross to Net Calculator', path: '/gross-to-net', desc: 'Calculate take-home pay from gross salary.' },
      { name: 'GST Calculator', path: '/gst-calculator', desc: 'Calculate Goods and Services Tax.' },
      { name: 'GST/QST Canada', path: '/gst-qst-canada', desc: 'Calculate combined Canadian sales taxes.' },
      { name: 'HELOC Calculator', path: '/heloc', desc: 'Home Equity Line of Credit.' },
      { name: 'Hourly to Salary', path: '/hourly-to-salary', desc: 'Convert hourly wage to annual salary.' },
      { name: 'House Affordability', path: '/house-affordability', desc: 'Find your home budget range.' },
      { name: 'Income Tax Calculator', path: '/income-tax', desc: 'Estimate your federal income tax liability.' },
      { name: 'Inflation Calculator', path: '/inflation', desc: 'Purchasing power over time.' },
      { name: 'Interest Rate', path: '/interest-rate', desc: 'Calculate APR and APY.' },
      { name: 'Investment Return', path: '/investment', desc: 'Project future wealth and growth.' },
      { name: 'IRA Calculator', path: '/ira', desc: 'Analyze traditional IRA contributions.' },
      { name: 'IRR Calculator', path: '/irr', desc: 'Internal Rate of Return for projects.' },
      { name: 'Lease Calculator', path: '/lease', desc: 'Compare buying vs leasing costs.' },
      { name: 'Loan Calculator', path: '/loan', desc: 'Estimate payments for any loan.' },
      { name: 'Lottery Tax Calculator', path: '/lottery-tax', desc: 'Calculate net payout after jackpot taxes.' },
      { name: 'Margin Calculator', path: '/margin', desc: 'Calculate markup and profit margins.' },
      { name: 'Marriage Tax', path: '/marriage-tax', desc: 'Check for marriage tax penalties/bonuses.' },
      { name: 'Mileage Reimbursement Calculator', path: '/mileage-reimbursement', desc: 'Calculate IRS standard mileage rates.' },
      { name: 'Missouri Sales Tax Calculator', path: '/missouri-sales-tax', desc: 'Calculate MO sales tax rates.' },
      { name: 'National Insurance', path: '/national-insurance-uk', desc: 'Calculate UK National Insurance contributions.' },
      { name: 'Modified AGI (MAGI)', path: '/magi-calculator', desc: 'Modified Adjusted Gross Income for eligibility.' },
      { name: 'Mortgage Calculator', path: '/mortgage', desc: 'Calculate monthly payments and amortization.' },
      { name: 'Mutual Fund', path: '/mutual-fund', desc: 'Analyze fund performance and fees.' },
      { name: 'Net to Gross Calculator', path: '/net-to-gross', desc: 'Calculate gross pay from target net amount.' },
      { name: 'Net Worth Calculator', path: '/net-worth', desc: 'Track total assets and liabilities.' },
      { name: 'New Jersey Sales Tax Calculator', path: '/new-jersey-sales-tax', desc: 'Calculate NJ sales tax for purchases.' },
      { name: 'New York Tax Calculator', path: '/new-york-tax', desc: 'Estimate NY state and city income tax.' },
      { name: 'Ohio Sales Tax Calculator', path: '/ohio-sales-tax', desc: 'Calculate OH sales tax by county.' },
      { name: 'Overtime Calculator', path: '/overtime-calculator', desc: 'Calculate time-and-a-half and double-time pay.' },
      { name: 'Payback Period', path: '/payback-period', desc: 'Time to recover your investment.' },
      { name: 'Payroll Calculator', path: '/payroll', desc: 'Calculate net pay and taxes for any salary.' },
      { name: 'Pension Calculator', path: '/pension', desc: 'Estimate future pension payments.' },
      { name: 'Present Value', path: '/present-value', desc: 'Calculate current value of future cash.' },
      { name: 'Refinance Calculator', path: '/refinance', desc: 'See if a new loan rate saves you money.' },
      { name: 'Retirement Planner', path: '/retirement', desc: 'Comprehensive retirement strategy tool.' },
      { name: 'RMD Calculator', path: '/rmd', desc: 'Required Minimum Distributions.' },
      { name: 'ROI Calculator', path: '/roi', desc: 'Measure investment performance.' },
      { name: 'Roth IRA Calculator', path: '/roth-ira', desc: 'Calculate Roth IRA growth and taxes.' },
      { name: 'Salary Calculator', path: '/salary', desc: 'Convert pay between different time periods.' },
      { name: 'Savings Calculator', path: '/savings', desc: 'Track your savings goals.' },
      { name: 'Social Security Calculator', path: '/social-security', desc: 'Estimate your retirement benefits.' },
      { name: 'Stamp Duty Land Tax (UK)', path: '/sdlt-calculator', desc: 'Calculate UK property purchase tax (SDLT).' },
      { name: 'Stock Return', path: '/stock-return', desc: 'Calculate total profit from shares.' },
      { name: 'Student Loan Calculator', path: '/student-loan', desc: 'Manage your education financing.' },
      { name: 'Take Home Pay', path: '/take-home-pay', desc: 'Estimate your actual take-home pay.' },
      { name: 'Take Home Pay UK', path: '/take-home-pay-uk', desc: 'Calculate UK net salary after tax and NI.' },
      { name: 'Tax Bracket Calculator', path: '/tax-bracket', desc: 'Find your marginal and effective tax rates.' },
      { name: 'UK Coin Weight', path: '/uk-coin-weight', desc: 'Calculate the weight and value of UK coinage.' },
      { name: 'VAT Calculator', path: '/vat', desc: 'Calculate Value Added Tax for purchases.' },
    ]
  },
  {
    title: 'Personal & Fun',
    slug: 'personal',
    description: 'Life metrics and entertaining curiosities. Our personal tools help you track unique milestones, compatibility, and day-to-day life calculations.',
    items: [
      { name: 'Dog Age Calculator', path: '/dog-age', desc: 'Convert dog years to human years.' },
      { name: 'Cat Age Calculator', path: '/cat-age', desc: 'Convert cat years to human years.' },
      { name: 'Angel Number', path: '/angel-number', desc: 'Discover your unique angel number.' },
      { name: 'Lucky Number', path: '/lucky-number', desc: 'Find your lucky number and color.' },
      { name: 'Friendship Calculator', path: '/friendship', desc: 'Test the strength of your friendship.' },
      { name: 'Star Sign Compatibility', path: '/star-sign-compatibility', desc: 'Check zodiac compatibility.' },
      { name: 'Name Compatibility', path: '/name-compatibility', desc: 'Test love match between two names.' },
      { name: 'Love Calculator', path: '/love-calculator', desc: 'Test the compatibility between two names.' },
      { name: 'Numerology', path: '/numerology', desc: 'Meaning behind your name and birth date.' },
      { name: 'Zodiac', path: '/zodiac', desc: 'Find your star sign and personality traits.' },
      { name: 'Anniversary Calculator', path: '/anniversary-calculator', desc: 'How long you\'ve been together.' },
      { name: 'Days Until', path: '/days-until', desc: 'Count down to any special event.' },
      { name: 'Business Days', path: '/business-days', desc: 'Count work days between two dates.' },
      { name: 'Chronological Age', path: '/chronological-age', desc: 'Calculate exact age in years, months, days.' },
      { name: 'Work Hours', path: '/work-hours', desc: 'Track your daily and weekly working time.' },
      { name: 'Time Card', path: '/time-card', desc: 'Calculate total hours and pay for a week.' },
      { name: 'Age Calculator', path: '/age', desc: 'Find out exactly how old you are.' },
    ]
  },
  {
    title: 'Insurance',
    slug: 'insurance',
    description: 'Secure your future with proper coverage. Our tools help you estimate how much life, health, or auto insurance you actually need.',
    items: [
      { name: 'Life Insurance', path: '/life-insurance', desc: 'Coverage for family protection.' },
      { name: 'Health Insurance', path: '/health-insurance', desc: 'Out-of-pocket and premium math.' },
      { name: 'Car Insurance', path: '/car-insurance', desc: 'Drive with financial peace of mind.' },
    ]
  },
  {
    title: 'Math',
    slug: 'math',
    description: 'From classroom basics to high-level analysis, our math tools simplify every calculation. We handle the heavy lifting for algebra, statistics, and geometry.',
    items: [
      { name: 'Quadratic Formula', path: '/quadratic-formula', desc: 'Solve quadratic equations step-by-step.' },
      { name: 'Pythagorean Theorem', path: '/pythagorean-theorem', desc: 'Solve sides of a right triangle.' },
      { name: 'GCF Calculator', path: '/gcf', desc: 'Find the greatest common factor.' },
      { name: 'LCM Calculator', path: '/lcm', desc: 'Find the least common multiple.' },
      { name: 'Big Number math', path: '/big-number', desc: 'Arithmetic with astronomical figures.' },
      { name: 'Matrix Calculator', path: '/matrix', desc: 'Advanced linear algebra operations.' },
      { name: 'Scientific Calculator', path: '/scientific', desc: 'Full engineering math suite.' },
      { name: 'Basic Calculator', path: '/basic-calculator', desc: 'Simple four-function tool.' },
      { name: 'GPA Calculator', path: '/gpa', desc: 'Track your academic performance.' },
      { name: 'Grade Calculator', path: '/grade-calculator', desc: 'Calculate final course grades.' },
      { name: 'Test Score', path: '/test-score', desc: 'Analyze percentage and letter grades.' },
      { name: 'Percentage Calculator', path: '/percentage', desc: 'Percent change and base math.' },
      { name: 'Percent Error', path: '/percent-error', desc: 'Measure precision in experiments.' },
      { name: 'Probability', path: '/probability', desc: 'Likelihood of statistical outcomes.' },
      { name: 'Permutation', path: '/permutation', desc: 'Count ordered arrangements.' },
      { name: 'Combination', path: '/combination', desc: 'Count unique selections.' },
      { name: 'Statistics', path: '/statistics', desc: 'Analyze datasets with precision.' },
      { name: 'Standard Deviation', path: '/standard-deviation', desc: 'Measure data variation.' },
      { name: 'P-value', path: '/p-value', desc: 'Determine statistical significance.' },
      { name: 'Fraction Calculator', path: '/fraction', desc: 'Simplify and solve with fractions.' },
      { name: 'Ratio Calculator', path: '/ratio', desc: 'Compare and simplify proportions.' },
      { name: 'Square Root', path: '/square-root', desc: 'Find roots for any base.' },
      { name: 'Log Calculator', path: '/log', desc: 'Natural and common logarithms.' },
      { name: 'Exponent Calculator', path: '/exponent', desc: 'Solve powers and roots.' },
      { name: 'Factor Calculator', path: '/factor', desc: 'Find all integer divisors.' },
      { name: 'Rounding', path: '/rounding', desc: 'Standard and scientific rounding.' },
      { name: 'Long Division', path: '/long-division', desc: 'Step-by-step division process.' },
      { name: 'Area Calculator', path: '/area', desc: 'Calculate area for 2D shapes.' },
      { name: 'Volume Calculator', path: '/volume', desc: 'Calculate volume for 3D objects.' },
      { name: 'Triangle', path: '/triangle', desc: 'Solve for angles and sides.' },
      { name: 'Circle', path: '/circle', desc: 'Radius, diameter, and area.' },
      { name: 'Surface Area', path: '/surface-area', desc: 'Calculate exterior 3D areas.' },
      { name: 'Significant Figures', path: '/significant-figures', desc: 'Maintain precision in results.' },
      { name: 'Slope Calculator', path: '/slope', desc: 'Find the incline of equations.' },
    ]
  },
  {
    title: 'Science',
    slug: 'science',
    description: 'Scientific precision at your fingertips. Our tools cover chemistry, physics, and engineering to help professionals and students verify complex results.',
    items: [
      { name: 'Activation Energy', path: '/activation-energy', desc: 'Calculate energy needed for chemical reactions.' },
      { name: 'Actual Yield', path: '/actual-yield', desc: 'Calculate the measured amount of product.' },
      { name: 'AFR (Air-Fuel Ratio)', path: '/afr-calculator', desc: 'Analyze combustion engine efficiency.' },
      { name: 'Arrhenius Equation', path: '/arrhenius-equation', desc: 'Calculate reaction rate and temperature dependencies.' },
      { name: 'Atom Calculator', path: '/atom-calculator', desc: 'Calculate subatomic particle counts.' },
      { name: 'Atom Economy', path: '/atom-economy', desc: 'Measure reaction efficiency and waste.' },
      { name: 'Atomic Mass', path: '/atomic-mass', desc: 'Calculate the mass of specific isotopes.' },
      { name: 'Average Atomic Mass', path: '/average-atomic-mass', desc: 'Weighted average of element isotopes.' },
      { name: 'Avogadro\'s Number', path: '/avogadros-number', desc: 'Standard constant for mole calculations.' },
      { name: 'Bond Order', path: '/bond-order', desc: 'Determine stability of chemical bonds.' },
      { name: 'BTU Calculator', path: '/btu', desc: 'Heat energy and HVAC requirements.' },
      { name: 'Chemical Equation Balancer', path: '/chemical-equation-balancer', desc: 'Balance stoichiometry for any reaction.' },
      { name: 'Chemical Name', path: '/chemical-name', desc: 'Nomenclature and formula verification.' },
      { name: 'Density Calculator', path: '/density', desc: 'Calculate mass, volume, and density.' },
      { name: 'Dew Point', path: '/dew-point', desc: 'Calculate air moisture saturation.' },
      { name: 'Effective Nuclear Charge', path: '/effective-nuclear-charge', desc: 'Z-eff calculation for valence electrons.' },
      { name: 'Electricity', path: '/electricity', desc: 'Energy, power, and cost math.' },
      { name: 'Electron Configuration', path: '/electron-configuration', desc: 'Map orbital distributions of atoms.' },
      { name: 'Electronegativity', path: '/electronegativity', desc: 'Pauling scale and chemical bonding tendencies.' },
      { name: 'Empirical Formula', path: '/empirical-formula', desc: 'Smallest whole number ratio of elements.' },
      { name: 'Equilibrium Constant', path: '/equilibrium-constant', desc: 'Calculate Kc for chemical systems.' },
      { name: 'Frequency', path: '/frequency', desc: 'Wavelength and period math.' },
      { name: 'Grams to Moles', path: '/grams-to-moles', desc: 'Quick weight-to-quantity conversion.' },
      { name: 'Heat Index', path: '/heat-index', desc: 'Apparent temperature and humidity.' },
      { name: 'Hydrogen Ion (pH)', path: '/hydrogen-ion-concentration', desc: 'Calculate pH from H+ concentration.' },
      { name: 'Kp Calculator', path: '/kp-calculator', desc: 'Equilibrium constant for partial pressures.' },
      { name: 'Mass Calculator', path: '/mass', desc: 'Convert and calculate object mass.' },
      { name: 'Molality', path: '/molality-calculator', desc: 'Moles of solute per kilogram of solvent.' },
      { name: 'Molar Mass', path: '/molar-mass', desc: 'Calculate total mass per mole of compound.' },
      { name: 'Molar Mass of Gas', path: '/molar-mass-of-gas', desc: 'Analyze gas density and pressure.' },
      { name: 'Molar Ratio', path: '/molar-ratio', desc: 'Analyze proportions in chemical equations.' },
      { name: 'Molarity Calculator', path: '/molarity', desc: 'Calculate concentration solutions.' },
      { name: 'Mole Calculator', path: '/mole-calculator', desc: 'Fundamental quantity for chemical amounts.' },
      { name: 'Mole Fraction', path: '/mole-fraction', desc: 'Ratio of moles in a mixture.' },
      { name: 'Molecular Weight', path: '/molecular-weight', desc: 'Molar mass of chemical compounds.' },
      { name: 'Moles to Atoms', path: '/moles-to-atoms', desc: 'Convert chemical quantity to particle count.' },
      { name: 'Net Ionic Equation', path: '/net-ionic-equation', desc: 'Simplify reactions to active species.' },
      { name: 'Normality', path: '/normality-calculator', desc: 'Equivalent concentration for acid-base math.' },
      { name: 'Ohms Law', path: '/ohms-law', desc: 'Solve for V, I, and R.' },
      { name: 'Percent Composition', path: '/percent-composition', desc: 'Mass percentage of each element.' },
      { name: 'Percent Ionic Character', path: '/percent-ionic-character', desc: 'Analyze bond polarity and types.' },
      { name: 'Percent Yield', path: '/percent-yield', desc: 'Compare actual vs theoretical results.' },
      { name: 'pKa Calculator', path: '/pka-calculator', desc: 'Acid dissociation constant analysis.' },
      { name: 'PPM to Molarity', path: '/ppm-to-molarity', desc: 'Convert parts per million to concentration.' },
      { name: 'Rate Constant', path: '/rate-constant', desc: 'Calculate k for chemical kinetics.' },
      { name: 'Reaction Quotient', path: '/reaction-quotient', desc: 'Determine system progress toward equilibrium.' },
      { name: 'Resistor Calculator', path: '/resistor', desc: 'Color code and value matching.' },
      { name: 'Speed Calculator', path: '/speed', desc: 'Velocity, time, and distance.' },
      { name: 'Temperature', path: '/temperature-converter', desc: 'C, F, and Kelvin conversions.' },
      { name: 'Theoretical Yield', path: '/theoretical-yield', desc: 'Calculate maximum possible product.' },
      { name: 'Voltage Drop', path: '/voltage-drop', desc: 'Estimate electrical line loss.' },
    ]
  },
  {
    title: 'Real Estate & Construction',
    slug: 'construction',
    description: 'Expert planning for property and professional engineering projects. Estimate building materials or analyze the structural and financial health of your capital investments.',
    items: [
      { name: 'Asphalt Calculator', path: '/asphalt', desc: 'Estimate volume and tonnage for paving.' },
      { name: 'Beam Deflection', path: '/beam-deflection', desc: 'Calculate stress and strain on structural beams.' },
      { name: 'Beam Load', path: '/beam-load', desc: 'Analyze structural weight distribution.' },
      { name: 'Bending Stress', path: '/bending-stress', desc: 'Calculate internal forces in structures.' },
      { name: 'Bolt Torque', path: '/bolt-torque', desc: 'Determine proper fastener tightness.' },
      { name: 'Box Fill', path: '/box-fill', desc: 'Electrical junction box capacity math.' },
      { name: 'BRRRR Calculator', path: '/brrrr', desc: 'Buy, Rehab, Rent, Refi, Repeat strategy.' },
      { name: 'Canadian Mortgage', path: '/canadian-mortgage', desc: 'CA compounding and payment rules.' },
      { name: 'Carbon Equivalent', path: '/carbon-equivalent', desc: 'Assess weldability of steel materials.' },
      { name: 'CFM Calculator', path: '/cfm', desc: 'Cubic Feet per Minute for ventilation.' },
      { name: 'Concrete Calculator', path: '/concrete', desc: 'Estimate volume for building slabs.' },
      { name: 'Concrete Driveway Cost', path: '/concrete-driveway-cost', desc: 'Estimate total paving expenses.' },
      { name: 'Crushed Stone', path: '/crushed-stone', desc: 'Calculate yardage for base layers.' },
      { name: 'Deck Calculator', path: '/deck', desc: 'Batten and joist material planning.' },
      { name: 'Door Header Size', path: '/door-header', desc: 'Determine structural support for openings.' },
      { name: 'Fence Calculator', path: '/fence', desc: 'Posts, rails, and material costs.' },
      { name: 'Floor Joist', path: '/floor-joist', desc: 'Calculate spans and spacing for floors.' },
      { name: 'Flooring Calculator', path: '/flooring', desc: 'Materials for wood, tile, carpet.' },
      { name: 'Gravel Calculator', path: '/gravel', desc: 'Tons and yards for generic projects.' },
      { name: 'Gravel Driveway', path: '/gravel-driveway', desc: 'Specific math for vehicle paths.' },
      { name: 'HELOC Calculator', path: '/heloc', desc: 'Home Equity Line of Credit.' },
      { name: 'Home Equity', path: '/home-equity', desc: 'Calculate property value minus debt.' },
      { name: 'House Affordability', path: '/house-affordability', desc: 'Find your home budget range.' },
      { name: 'Insulation Calculator', path: '/insulation', desc: 'Calculate R-value and material needs.' },
      { name: 'Junction Box Sizing', path: '/junction-box-sizing', desc: 'Electrical code compliance for wiring.' },
      { name: 'K-Factor (Metal)', path: '/k-factor-sheet-metal', desc: 'Bend allowance for industrial fabrication.' },
      { name: 'Material Removal Rate', path: '/mrr-calculator', desc: 'CNC and machining efficiency metrics.' },
      { name: 'Mortgage Calculator', path: '/mortgage', desc: 'Primary mortgage payment analysis.' },
      { name: 'Mulch Calculator', path: '/mulch', desc: 'Estimate volume for landscaping.' },
      { name: 'Paint Calculator', path: '/paint', desc: 'Estimate gallons and coverage.' },
      { name: 'Pitch Diameter', path: '/pitch-diameter', desc: 'Critical dimensions for threads and gears.' },
      { name: 'Punch Force', path: '/punch-force', desc: 'Pressure required for metal stamps.' },
      { name: 'Quiz: Beam Load', path: '/beam-load-quiz', desc: 'Test your structural engineering knowledge.' },
      { name: 'Rent Calculator', path: '/rent', desc: 'Determine affordable monthly rent.' },
      { name: 'Rental Property', path: '/rental-property', desc: 'Analyze investment profit and ROI.' },
      { name: 'Rivet Size', path: '/rivet-size', desc: 'Select correct fasteners for assembly.' },
      { name: 'Road Base', path: '/road-base', desc: 'Calculate subsurface material tonnage.' },
      { name: 'Roofing Calculator', path: '/roofing', desc: 'Estimate shingles and materials.' },
      { name: 'Spindle Speed', path: '/spindle-speed', desc: 'Machining RPM for different materials.' },
      { name: 'Square Footage', path: '/square-footage', desc: 'Calculate floor and wall areas.' },
      { name: 'Stair Calculator', path: '/stair', desc: 'Rises, runs, and stringer lengths.' },
      { name: 'Tile Calculator', path: '/tile', desc: 'Estimate count and waste factors.' },
      { name: 'UK Mortgage', path: '/mortgage-uk', desc: 'Specific UK mortgage rules/taxes.' },
      { name: 'Wallpaper', path: '/wallpaper', desc: 'Analyze roll count and coverage.' },
    ]
  },
  {
    title: 'Everyday Tools',
    slug: 'everyday',
    description: 'Utilities for the modern lifestyle. Secure your digital world, manage your time, or handle small mathematical tasks in your daily routine.',
    items: [
      { name: 'Time Calculator', path: '/time', desc: 'Durations and time additions.' },
      { name: 'Password Generator', path: '/password-generator', desc: 'Secure random credentials.' },
      { name: 'Word Counter', path: '/word-counter', desc: 'Count chars, words, reading time.' },
      { name: 'Hours Calculator', path: '/hours', desc: 'Daily and weekly work tracking.' },
      { name: 'Amazon FBA', path: '/amazon-fba', desc: 'E-commerce seller profit tools.' },
      { name: 'Percentage Off', path: '/percentage-off', desc: 'Quick holiday deal math.' },
      { name: 'Height Calculator', path: '/height', desc: 'Convert and predict stature.' },
      { name: 'Bra Size', path: '/bra-size', desc: 'Measure for comfort and support.' },
      { name: 'Dice Roller', path: '/dice-roller', desc: 'Virtual dice for tabletop games.' },
      { name: 'GDP Calculator', path: '/gdp', desc: 'Economic output analysis.' },
      { name: 'Tip Calculator', path: '/tip', desc: 'Split the bill and gratuity.' },
      { name: 'Discount Calculator', path: '/discount', desc: 'Retail savings and final prices.' },
      { name: 'IP Subnet', path: '/ip-subnet', desc: 'Network mask and address math.' },
      { name: 'Gratuity Calculator', path: '/gratuity-calculator', desc: 'Calculate correct tips for service.' },
    ]
  },
  {
    title: 'Automotive',
    slug: 'automotive',
    description: 'Keep your vehicle running efficiently. Manage fuel budgets, track depreciation, and analyze the true cost of car ownership.',
    items: [
      { name: 'Car Depreciation', path: '/car-depreciation', desc: 'Vehicle value loss over time.' },
      { name: 'Car Lease', path: '/car-lease', desc: 'Auto leasing payment breakdown.' },
      { name: 'Engine Horsepower', path: '/engine-horsepower', desc: 'Torque and RPM performance metrics.' },
      { name: 'Fuel Cost', path: '/fuel-cost', desc: 'Price per mile and trip totals.' },
      { name: 'MPG Calculator', path: '/mpg', desc: 'Calculate fuel efficiency trends.' },
      { name: 'Road Trip Cost', path: '/road-trip-cost', desc: 'Distance and fuel price planning.' },
      { name: 'Tire Size', path: '/tire-size', desc: 'Diameter and speedo adjustments.' },
      { name: 'Vehicle Tax', path: '/vehicle-tax', desc: 'Sales tax and registration costs.' },
    ]
  },
  {
    title: 'Health & Fitness',
    slug: 'health',
    description: 'Monitor your physical benchmarks and nutritional health with precision. Our suite of clinical and fitness tools helps you understand your metabolism and stay on track with your body goals.',
    items: [
      { name: 'Added Sugar Intake', path: '/added-sugar-intake', desc: 'Calculate recommended maximum daily sugar.' },
      { name: 'Arm Body Fat', path: '/arm-body-fat', desc: 'Analyze upper body composition.' },
      { name: 'BAC Calculator', path: '/bac', desc: 'Estimate Blood Alcohol Concentration.' },
      { name: 'BEE Calculator', path: '/bee-calculator', desc: 'Basal Energy Expenditure analysis.' },
      { name: 'BMI Calculator', path: '/bmi', desc: 'Body Mass Index for adults.' },
      { name: 'BMR (Mifflin St Jeor)', path: '/bmr', desc: 'Basal Metabolic Rate formula.' },
      { name: 'Body Fat Calculator', path: '/body-fat', desc: 'Estimate body fat percentage.' },
      { name: 'Body Type', path: '/body-type', desc: 'Identify your somatic body category.' },
      { name: 'Calorie Calculator', path: '/calorie', desc: 'Estimate daily energy expenditure.' },
      { name: 'Calorie Deficit', path: '/calorie-deficit', desc: 'Calculate calories needed for weight loss.' },
      { name: 'Calorie Intake (Simple)', path: '/calorie-intake', desc: 'Quick daily calorie estimation.' },
      { name: 'Calories Burned', path: '/calories-burned', desc: 'Track energy used during exercise.' },
      { name: 'Carb Calculator', path: '/carbohydrate-calculator', desc: 'Calculate daily carb requirements.' },
      { name: 'Diet Risk Score', path: '/diet-risk-score', desc: 'Analyze nutritional habits.' },
      { name: 'DRI Calculator', path: '/dri-calculator', desc: 'Dietary Reference Intake for nutrients.' },
      { name: 'Due Date', path: '/due-date', desc: 'Find your expected delivery date.' },
      { name: 'EER Calculator', path: '/eer-calculator', desc: 'Estimated Energy Requirement.' },
      { name: 'Fat Intake', path: '/fat-intake', desc: 'Calculate daily healthy fat needs.' },
      { name: 'Fertility Calculator', path: '/fertility', desc: 'Manage your reproductive health.' },
      { name: 'Fiber Calculator', path: '/fiber-calculator', desc: 'Calculate daily dietary fiber needs.' },
      { name: 'Gastric Sleeve Weight Loss', path: '/gastric-sleeve-weight-loss', desc: 'Post-surgery weight loss projection.' },
      { name: 'Harris-Benedict (BMR)', path: '/harris-benedict', desc: 'Legacy BMR estimation formula.' },
      { name: 'Ideal Weight', path: '/ideal-weight', desc: 'Find your target body weight.' },
      { name: 'IIFYM Calculator', path: '/iifym', desc: 'If It Fits Your Macros strategy.' },
      { name: 'Katch-McArdle', path: '/katch-mcardle', desc: 'BMR based on lean body mass.' },
      { name: 'Keto Calculator', path: '/keto-calculator', desc: 'Ketogenic diet macronutrient ratios.' },
      { name: 'Lean Body Mass', path: '/lean-body-mass', desc: 'Calculate weight excluding fat.' },
      { name: 'Macro Calculator', path: '/macro', desc: 'Calculate protein, carbs, and fat ratios.' },
      { name: 'Maintenance Calorie', path: '/maintenance-calorie', desc: 'Calories needed to maintain weight.' },
      { name: 'Meal Calorie', path: '/meal-calorie', desc: 'Break down calories per meal.' },
      { name: 'Micronutrient Calculator', path: '/micronutrient-calculator', desc: 'Track essential vitamins and minerals.' },
      { name: 'Net Carbs', path: '/net-carbs', desc: 'Calculate carbs minus fiber/sugar alcohols.' },
      { name: 'One Rep Max', path: '/one-rep-max', desc: 'Estimate your maximum lifting power.' },
      { name: 'Ovulation', path: '/ovulation', desc: 'Track your most fertile days.' },
      { name: 'Pace Calculator', path: '/pace', desc: 'Calculate running pace and speed.' },
      { name: 'Pregnancy Calculator', path: '/pregnancy', desc: 'Estimate your baby\'s due date.' },
      { name: 'Pregnancy Weight Gain', path: '/pregnancy-weight-gain', desc: 'Monitor healthy gestation growth.' },
      { name: 'Protein Calculator', path: '/protein', desc: 'Check daily protein requirements.' },
      { name: 'Quarantine Activity', path: '/quarantine-activity', desc: 'Adjust needs for low-activity periods.' },
      { name: 'Quiz: Harris-Benedict', path: '/harris-benedict-quiz', desc: 'Test your metabolic knowledge.' },
      { name: 'RMR Calculator', path: '/rmr', desc: 'Resting Metabolic Rate analysis.' },
      { name: 'Sleep Calculator', path: '/sleep', desc: 'Find the best time to wake up or sleep.' },
      { name: 'Sobriety Calculator', path: '/sobriety', desc: 'Track your journey and progress.' },
      { name: 'Sodium in Salt', path: '/sodium-in-salt', desc: 'Convert salt weight to sodium content.' },
      { name: 'Target Heart Rate', path: '/target-heart-rate', desc: 'Monitor your optimal workout intensity.' },
      { name: 'TDEE Calculator', path: '/tdee', desc: 'Total Daily Energy Expenditure.' },
      { name: 'Vitamin Calculator', path: '/vitamin-calculator', desc: 'General vitamin goal assessment.' },
      { name: 'Vitamin A', path: '/vitamin-a-calculator', desc: 'Specific Vitamin A requirement math.' },
      { name: 'Vitamin D', path: '/vitamin-d-calculator', desc: 'Specific Vitamin D requirement math.' },
      { name: 'VO2 Max', path: '/vo2-max', desc: 'Measure your cardiovascular fitness.' },
      { name: 'Waist To Hip', path: '/waist-to-hip', desc: 'Analyze body shape and health risk.' },
      { name: 'Water Intake', path: '/water-intake', desc: 'Find your daily hydration needs.' },
      { name: 'Weight Gain', path: '/weight-gain-calculator', desc: 'Healthy weight gain strategies.' },
      { name: 'Weight Watchers Points', path: '/weight-watchers-points', desc: 'Estimate system point values.' },
    ]
  },
  {
    title: 'Converters',
    slug: 'converters',
    description: 'Instant unit transformation. Convert length, weight, tech formats, and historical numbering systems with total accuracy.',
    items: [
      { name: 'Unit Converter', path: '/unit-converter', desc: 'Metric and Imperial conversions.' },
      { name: 'Currency Converter', path: '/currency-converter', desc: 'Live exchange rate calculations.' },
      { name: 'Roman Numerals', path: '/roman-numeral-converter', desc: 'Convert to and from Arabic numerals.' },
      { name: 'Hex Converter', path: '/hex', desc: 'Hex, Dec, and Bin conversions.' },
      { name: 'Binary Converter', path: '/binary', desc: 'Logic and base-2 math.' },
      { name: 'Base64 Converter', path: '/base64', desc: 'Encode and decode binary data.' },
      { name: 'URL Converter', path: '/url-converter', desc: 'Safe web address strings.' },
      { name: 'Shoe Size', path: '/shoe-size-conversion', desc: 'Global footwear standards.' },
      { name: 'Time Zone', path: '/time-zone-converter', desc: 'Global sync for meetings/travel.' },
      { name: 'Scientific Notation', path: '/scientific-notation', desc: 'Standard power-of-10 format.' },
    ]
  },
  {
    title: 'Business & Marketing',
    slug: 'business',
    description: 'Optimize your operations and scale your growth. Our business suite covers everything from SaaS metrics and marketing performance to HR analytics and corporate finance.',
    items: [
      { name: '3D Printer - Buy vs Outsource', path: '/3d-printer-buy-vs-outsource', desc: 'Decide whether to manufacture in-house or outsource.' },
      { name: 'Absence Percentage', path: '/absence-percentage', desc: 'Calculate the rate of employee absenteeism.' },
      { name: 'Accumulated Depreciation', path: '/accumulated-depreciation', desc: 'Track total asset value loss over time.' },
      { name: 'Additional Funds Needed', path: '/additional-funds-needed', desc: 'Estimate external financing requirements.' },
      { name: 'Attrition Rate', path: '/attrition-rate', desc: 'Calculate staff turnover percentage.' },
      { name: 'Average Collection Period', path: '/average-collection-period', desc: 'Measure time to collect accounts receivable.' },
      { name: 'Average Fixed Cost', path: '/average-fixed-cost', desc: 'Calculate overhead per unit produced.' },
      { name: 'Bounce Rate', path: '/bounce-rate', desc: 'Analyze website visitor engagement.' },
      { name: 'Bradford Factor', path: '/bradford-factor', desc: 'Measure the impact of short-term absences.' },
      { name: 'Break-even', path: '/break-even', desc: 'Find the point where revenue equals costs.' },
      { name: 'Build vs. Buy', path: '/build-vs-buy', desc: 'Analyze software and hardware procurement.' },
      { name: 'Burndown Chart', path: '/burndown-chart', desc: 'Track remaining work in agile projects.' },
      { name: 'Burn Rate', path: '/burn-rate', desc: 'Calculate monthly cash consumption.' },
      { name: 'Business Budget', path: '/business-budget', desc: 'Manage corporate income and expenses.' },
      { name: 'Business Valuation', path: '/business-valuation', desc: 'Estimate the total worth of a company.' },
      { name: 'Churn Rate', path: '/churn-rate', desc: 'Measure customer or subscriber loss.' },
      { name: 'Consulting Fees', path: '/consulting-fees', desc: 'Calculate hourly and project-based rates.' },
      { name: 'Contribution Margin', path: '/contribution-margin', desc: 'Calculate profit after variable costs.' },
      { name: 'Conversion Rate', path: '/conversion-rate', desc: 'Measure percentage of successful actions.' },
      { name: 'Cost of Doing Business', path: '/cost-of-doing-business', desc: 'Calculate total operating expenses.' },
      { name: 'Cost of Goods Sold', path: '/cogs', desc: 'Track direct costs of product manufacturing.' },
      { name: 'CPA Calculator', path: '/cpa', desc: 'Calculate cost per acquisition.' },
      { name: 'CPC and CPM', path: '/cpc-cpm', desc: 'Compare digital advertising costs.' },
      { name: 'CPM Calculator', path: '/cpm', desc: 'Calculate cost per thousand impressions.' },
      { name: 'CTR Calculator', path: '/ctr', desc: 'Measure click-through rate performance.' },
      { name: 'CAC Calculator', path: '/cac', desc: 'Calculate customer acquisition cost.' },
      { name: 'Customer Retention Rate', path: '/customer-retention', desc: 'Measure customer loyalty over time.' },
      { name: 'Direct Material Price Variance', path: '/material-variance', desc: 'Analyze manufacturing cost differences.' },
      { name: 'EVM Calculator', path: '/evm', desc: 'Earned Value Management for projects.' },
      { name: 'Effective Corporate Tax Rate', path: '/corporate-tax', desc: 'Calculate actual tax liability.' },
      { name: 'EMV Calculator', path: '/emv', desc: 'Calculate expected monetary value.' },
      { name: 'Exit Rate', path: '/exit-rate', desc: 'Track where users leave your site.' },
      { name: 'FIFO Calculator', path: '/fifo', desc: 'Inventory valuation using First-In First-Out.' },
      { name: 'FTE Calculator', path: '/fte', desc: 'Calculate Full-Time Equivalent staff.' },
      { name: 'GMROI Calculator', path: '/gmroi', desc: 'Gross margin return on investment.' },
      { name: 'Google AdSense', path: '/adsense', desc: 'Estimate website advertising earnings.' },
      { name: 'GRP Calculator', path: '/grp', desc: 'Measure Gross Rating Points for ads.' },
      { name: 'HHI Calculator', path: '/hhi', desc: 'Measure market competition levels.' },
      { name: 'High-Low Method', path: '/high-low', desc: 'Separate fixed and variable costs.' },
      { name: 'Labor Cost', path: '/labor-cost', desc: 'Calculate total employee expenses.' },
      { name: 'Lemonade Stand', path: '/lemonade-stand', desc: 'Simple business simulation tool.' },
      { name: 'Lerner Index', path: '/lerner-index', desc: 'Measure market power of a firm.' },
      { name: 'Liquid Net Worth', path: '/liquid-net-worth', desc: 'Assets available as immediate cash.' },
      { name: 'Man-Hours', path: '/man-hours', desc: 'Calculate total project effort.' },
      { name: 'Days Off', path: '/days-off', desc: 'Track employee vacation and leave.' },
      { name: 'Online Marketing Conversion', path: '/marketing-conversion', desc: 'Track digital sales funnels.' },
      { name: 'Operating Asset Turnover', path: '/operating-asset-turnover', desc: 'Measure asset utilization efficiency.' },
      { name: 'Parking Ratio', path: '/parking-ratio', desc: 'Calculate required commercial parking.' },
      { name: 'Pre and Post Money Valuation', path: '/pre-post-valuation', desc: 'Analyze venture capital funding.' },
      { name: 'PVGO Calculator', path: '/pvgo', desc: 'Present Value of Growth Opportunities.' },
      { name: 'Price / Quantity', path: '/price-quantity', desc: 'Calculate total volume discounts.' },
      { name: 'Profitability Index', path: '/profitability-index', desc: 'Measure relative profitability.' },
      { name: 'Revenue Per Employee', path: '/revenue-per-employee', desc: 'Measure workforce productivity.' },
      { name: 'ROAS Calculator', path: '/roas', desc: 'Return on Advertising Spend.' },
      { name: 'SaaS Lifetime Value', path: '/saas-ltv', desc: 'Estimate total customer revenue.' },
      { name: 'SaaS Metrics', path: '/saas-metrics', desc: 'Comprehensive recurring revenue tools.' },
      { name: 'Sales Commission', path: '/sales-commission', desc: 'Calculate payouts for sales teams.' },
      { name: 'Sell-Through Rate', path: '/sell-through', desc: 'Measure inventory sales velocity.' },
      { name: 'Smoker\'s CTC', path: '/smoker-ctc', desc: 'Calculate total cost to company.' },
      { name: 'Software Contract Value', path: '/acv-tcv', desc: 'Analyze annual and total contract values.' },
      { name: 'Tenure', path: '/tenure', desc: 'Calculate duration of employment.' },
      { name: 'Turnover Rate', path: '/turnover-rate', desc: 'Measure employee churn velocity.' },
      { name: 'Website Ad Revenue', path: '/website-ad-revenue', desc: 'Project earnings from web traffic.' },
      { name: 'YouTube Money', path: '/youtube-money', desc: 'Estimate channel ad revenue.' },
    ]
  }
];
