export interface CalculatorItem {
  name: string;
  path: string;
  desc: string;
}

export interface CategoryData {
  title: string;
  slug: string;
  description: string;
  items: CalculatorItem[];
}

export const CATEGORIES: CategoryData[] = [
  {
    title: 'Finance & Investment',
    slug: 'finance',
    description: 'Grow your wealth and manage your debt with precision. Our finance suite covers everything from daily budgeting to complex investment analysis and tax planning.',
    items: [
      { name: 'Payroll Calculator', path: '/payroll', desc: 'Calculate net pay and taxes for any salary.' },
      { name: 'Take Home Pay', path: '/take-home-pay', desc: 'Estimate your actual take-home pay.' },
      { name: 'Income Tax', path: '/income-tax', desc: 'Estimate your federal income tax liability.' },
      { name: 'Tax Bracket', path: '/tax-bracket', desc: 'Find your marginal and effective tax rates.' },
      { name: 'Capital Gains Tax', path: '/capital-gains-tax', desc: 'Calculate tax on investment profits.' },
      { name: 'VAT Calculator', path: '/vat', desc: 'Calculate Value Added Tax for purchases.' },
      { name: 'Estate Tax', path: '/estate-tax', desc: 'Plan for inheritance and estate transfers.' },
      { name: 'Marriage Tax', path: '/marriage-tax', desc: 'Check for marriage tax penalties/bonuses.' },
      { name: 'Retirement Planner', path: '/retirement', desc: 'Comprehensive retirement strategy tool.' },
      { name: '401k Calculator', path: '/401k', desc: 'Estimate future 401k balance.' },
      { name: 'Roth IRA', path: '/roth-ira', desc: 'Calculate Roth IRA growth and taxes.' },
      { name: 'IRA Calculator', path: '/ira', desc: 'Analyze traditional IRA contributions.' },
      { name: 'RMD Calculator', path: '/rmd', desc: 'Required Minimum Distributions.' },
      { name: 'Pension Calculator', path: '/pension', desc: 'Estimate future pension payments.' },
      { name: 'Social Security', path: '/social-security', desc: 'Estimate your retirement benefits.' },
      { name: 'Investment Return', path: '/investment', desc: 'Project future wealth and growth.' },
      { name: 'ROI Calculator', path: '/roi', desc: 'Measure investment performance.' },
      { name: 'Compound Interest', path: '/compound-interest', desc: 'Calculate investment growth over time.' },
      { name: 'Dividend Calculator', path: '/dividend', desc: 'Estimate regular income from stocks.' },
      { name: 'Bond Calculator', path: '/bond', desc: 'Calculate yield and maturity of bonds.' },
      { name: 'Mutual Fund', path: '/mutual-fund', desc: 'Analyze fund performance and fees.' },
      { name: 'Stock Return', path: '/stock-return', desc: 'Calculate total profit from shares.' },
      { name: 'Cryptocurrency', path: '/crypto', desc: 'Track gains across digital assets.' },
      { name: 'Bitcoin Profit', path: '/bitcoin-profit', desc: 'Calculate BTC investment gains.' },
      { name: 'Savings Calculator', path: '/savings', desc: 'Track your savings goals.' },
      { name: 'CD Calculator', path: '/cd', desc: 'Certificate of Deposit earnings.' },
      { name: 'Loan Calculator', path: '/loan', desc: 'Estimate payments for any loan.' },
      { name: 'Personal Loan', path: '/personal-loan', desc: 'Calculate payments for private loans.' },
      { name: 'Business Loan', path: '/business-loan', desc: 'Analyze commercial financing costs.' },
      { name: 'Boat Loan', path: '/boat-loan', desc: 'Finance your nautical adventures.' },
      { name: 'Credit Card Payoff', path: '/credit-card', desc: 'Plan your debt payoff strategy.' },
      { name: 'Debt Consolidation', path: '/debt-consolidation', desc: 'Analyze if combining loans saves money.' },
      { name: 'Debt Payoff', path: '/debt-payoff', desc: 'Strategize your exit from debt.' },
      { name: 'Student Loan', path: '/student-loan', desc: 'Manage your education financing.' },
      { name: 'College Cost', path: '/college-cost', desc: 'Estimate future tuition and expenses.' },
      { name: 'Autopay Calculator', path: '/auto-loan', desc: 'Plan your vehicle purchase payments.' },
      { name: 'Lease Calculator', path: '/lease', desc: 'Compare buying vs leasing costs.' },
      { name: 'Refinance', path: '/refinance', desc: 'See if a new loan rate saves you money.' },
      { name: 'Net Worth', path: '/net-worth', desc: 'Track total assets and liabilities.' },
      { name: 'Budget Calculator', path: '/budget', desc: 'Organize your monthly spending.' },
      { name: 'Inflation Calculator', path: '/inflation', desc: 'Purchasing power over time.' },
      { name: 'Interest Rate', path: '/interest-rate', desc: 'Calculate APR and APY.' },
      { name: 'Present Value', path: '/present-value', desc: 'Calculate current value of future cash.' },
      { name: 'Future Value', path: '/future-value', desc: 'Calculate future wealth from principal.' },
      { name: 'Margin Calculator', path: '/margin', desc: 'Calculate markup and profit margins.' },
      { name: 'Commission', path: '/commission', desc: 'Calculate sales rep earnings.' },
      { name: 'IRR Calculator', path: '/irr', desc: 'Internal Rate of Return for projects.' },
      { name: 'Payback Period', path: '/payback-period', desc: 'Time to recover your investment.' },
      { name: 'Salary Calculator', path: '/salary', desc: 'Convert pay between different time periods.' },
      { name: 'Mortgage Calculator', path: '/mortgage', desc: 'Calculate monthly payments and amortization.' },
    ]
  },
  {
    title: 'Personal & Fun',
    slug: 'personal',
    description: 'Life metrics and entertaining curiosities. Our personal tools help you track unique milestones, compatibility, and day-to-day life calculations.',
    items: [
      { name: 'Dog Age Calculator', path: '/dog-age', desc: 'Convert dog years to human years.' },
      { name: 'Cat Age Calculator', path: '/cat-age', desc: 'Convert cat years to human years.' },
      { name: 'Angel Number', path: '/angel-number', desc: 'Discover your unique angel number.' },
      { name: 'Lucky Number', path: '/lucky-number', desc: 'Find your lucky number and color.' },
      { name: 'Friendship Calculator', path: '/friendship', desc: 'Test the strength of your friendship.' },
      { name: 'Star Sign Compatibility', path: '/star-sign-compatibility', desc: 'Check zodiac compatibility.' },
      { name: 'Name Compatibility', path: '/name-compatibility', desc: 'Test love match between two names.' },
      { name: 'Love Calculator', path: '/love-calculator', desc: 'Test the compatibility between two names.' },
      { name: 'Numerology', path: '/numerology', desc: 'Meaning behind your name and birth date.' },
      { name: 'Zodiac', path: '/zodiac', desc: 'Find your star sign and personality traits.' },
      { name: 'Anniversary Calculator', path: '/anniversary-calculator', desc: 'How long you\'ve been together.' },
      { name: 'Days Until', path: '/days-until', desc: 'Count down to any special event.' },
      { name: 'Business Days', path: '/business-days', desc: 'Count work days between two dates.' },
      { name: 'Chronological Age', path: '/chronological-age', desc: 'Calculate exact age in years, months, days.' },
      { name: 'Work Hours', path: '/work-hours', desc: 'Track your daily and weekly working time.' },
      { name: 'Time Card', path: '/time-card', desc: 'Calculate total hours and pay for a week.' },
      { name: 'Age Calculator', path: '/age', desc: 'Find out exactly how old you are.' },
    ]
  },
  {
    title: 'Health & Fitness',
    slug: 'health',
    description: 'Monitor your physical benchmarks with precision. Our clinical and fitness tools help you understand your body and stay on track with your health goals.',
    items: [
      { name: 'BMI Calculator', path: '/bmi', desc: 'Body Mass Index for adults.' },
      { name: 'BMR Calculator', path: '/bmr', desc: 'Basal Metabolic Rate.' },
      { name: 'Ideal Weight', path: '/ideal-weight', desc: 'Find your target body weight.' },
      { name: 'Body Fat Calculator', path: '/body-fat', desc: 'Estimate body fat percentage.' },
      { name: 'Arm Body Fat', path: '/arm-body-fat', desc: 'Analyze upper body composition.' },
      { name: 'TDEE Calculator', path: '/tdee', desc: 'Total Daily Energy Expenditure.' },
      { name: 'Macro Calculator', path: '/macro', desc: 'Calculate protein, carbs, and fat ratios.' },
      { name: 'Calorie Calculator', path: '/calorie', desc: 'Estimate daily energy expenditure.' },
      { name: 'Calories Burned', path: '/calories-burned', desc: 'Track energy used during exercise.' },
      { name: 'One Rep Max', path: '/one-rep-max', desc: 'Estimate your maximum lifting power.' },
      { name: 'Protein Calculator', path: '/protein', desc: 'Check daily protein requirements.' },
      { name: 'Water Intake', path: '/water-intake', desc: 'Find your daily hydration needs.' },
      { name: 'Pace Calculator', path: '/pace', desc: 'Calculate running pace and speed.' },
      { name: 'Target Heart Rate', path: '/target-heart-rate', desc: 'Monitor your optimal workout intensity.' },
      { name: 'VO2 Max', path: '/vo2-max', desc: 'Measure your cardiovascular fitness.' },
      { name: 'Waist To Hip', path: '/waist-to-hip', desc: 'Analyze body shape and health risk.' },
      { name: 'Lean Body Mass', path: '/lean-body-mass', desc: 'Calculate weight excluding fat.' },
      { name: 'Pregnancy Calculator', path: '/pregnancy', desc: 'Estimate your baby\'s due date.' },
      { name: 'Due Date', path: '/due-date', desc: 'Find your expected delivery date.' },
      { name: 'Ovulation', path: '/ovulation', desc: 'Track your most fertile days.' },
      { name: 'Fertility Calculator', path: '/fertility', desc: 'Manage your reproductive health.' },
      { name: 'Pregnancy Weight Gain', path: '/pregnancy-weight-gain', desc: 'Monitor healthy gestation growth.' },
      { name: 'Sleep Calculator', path: '/sleep', desc: 'Find the best time to wake up or sleep.' },
      { name: 'Sobriety Calculator', path: '/sobriety', desc: 'Track your journey and progress.' },
      { name: 'BAC Calculator', path: '/bac', desc: 'Estimate Blood Alcohol Concentration.' },
      { name: 'Body Type', path: '/body-type', desc: 'Identify your somatic body category.' },
    ]
  },
  {
    title: 'Math',
    slug: 'math',
    description: 'From classroom basics to high-level analysis, our math tools simplify every calculation. We handle the heavy lifting for algebra, statistics, and geometry.',
    items: [
      { name: 'Quadratic Formula', path: '/quadratic-formula', desc: 'Solve quadratic equations step-by-step.' },
      { name: 'Pythagorean Theorem', path: '/pythagorean-theorem', desc: 'Solve sides of a right triangle.' },
      { name: 'GCF Calculator', path: '/gcf', desc: 'Find the greatest common factor.' },
      { name: 'LCM Calculator', path: '/lcm', desc: 'Find the least common multiple.' },
      { name: 'Big Number math', path: '/big-number', desc: 'Arithmetic with astronomical figures.' },
      { name: 'Matrix Calculator', path: '/matrix', desc: 'Advanced linear algebra operations.' },
      { name: 'Scientific Calculator', path: '/scientific', desc: 'Full engineering math suite.' },
      { name: 'Basic Calculator', path: '/basic-calculator', desc: 'Simple four-function tool.' },
      { name: 'GPA Calculator', path: '/gpa', desc: 'Track your academic performance.' },
      { name: 'Grade Calculator', path: '/grade-calculator', desc: 'Calculate final course grades.' },
      { name: 'Test Score', path: '/test-score', desc: 'Analyze percentage and letter grades.' },
      { name: 'Percentage Calculator', path: '/percentage', desc: 'Percent change and base math.' },
      { name: 'Percent Error', path: '/percent-error', desc: 'Measure precision in experiments.' },
      { name: 'Probability', path: '/probability', desc: 'Likelihood of statistical outcomes.' },
      { name: 'Permutation', path: '/permutation', desc: 'Count ordered arrangements.' },
      { name: 'Combination', path: '/combination', desc: 'Count unique selections.' },
      { name: 'Statistics', path: '/statistics', desc: 'Analyze datasets with precision.' },
      { name: 'Standard Deviation', path: '/standard-deviation', desc: 'Measure data variation.' },
      { name: 'P-value', path: '/p-value', desc: 'Determine statistical significance.' },
      { name: 'Fraction Calculator', path: '/fraction', desc: 'Simplify and solve with fractions.' },
      { name: 'Ratio Calculator', path: '/ratio', desc: 'Compare and simplify proportions.' },
      { name: 'Square Root', path: '/square-root', desc: 'Find roots for any base.' },
      { name: 'Log Calculator', path: '/log', desc: 'Natural and common logarithms.' },
      { name: 'Exponent Calculator', path: '/exponent', desc: 'Solve powers and roots.' },
      { name: 'Factor Calculator', path: '/factor', desc: 'Find all integer divisors.' },
      { name: 'Rounding', path: '/rounding', desc: 'Standard and scientific rounding.' },
      { name: 'Long Division', path: '/long-division', desc: 'Step-by-step division process.' },
      { name: 'Area Calculator', path: '/area', desc: 'Calculate area for 2D shapes.' },
      { name: 'Volume Calculator', path: '/volume', desc: 'Calculate volume for 3D objects.' },
      { name: 'Triangle', path: '/triangle', desc: 'Solve for angles and sides.' },
      { name: 'Circle', path: '/circle', desc: 'Radius, diameter, and area.' },
      { name: 'Surface Area', path: '/surface-area', desc: 'Calculate exterior 3D areas.' },
      { name: 'Significant Figures', path: '/significant-figures', desc: 'Maintain precision in results.' },
      { name: 'Slope Calculator', path: '/slope', desc: 'Find the incline of equations.' },
    ]
  },
  {
    title: 'Science',
    slug: 'science',
    description: 'Scientific precision at your fingertips. Our tools cover chemistry, electricity, and classical mechanics to help professionals and students verify results.',
    items: [
      { name: 'Density Calculator', path: '/density', desc: 'Calculate mass, volume, and density.' },
      { name: 'Mass Calculator', path: '/mass', desc: 'Convert and calculate object mass.' },
      { name: 'Speed Calculator', path: '/speed', desc: 'Velocity, time, and distance.' },
      { name: 'Molarity Calculator', path: '/molarity', desc: 'Calculate concentration solutions.' },
      { name: 'Molecular Weight', path: '/molecular-weight', desc: 'Molar mass of chemical compounds.' },
      { name: 'Ohms Law', path: '/ohms-law', desc: 'Solve for V, I, and R.' },
      { name: 'Resistor Calculator', path: '/resistor', desc: 'Color code and value matching.' },
      { name: 'Voltage Drop', path: '/voltage-drop', desc: 'Estimate electrical line loss.' },
      { name: 'Electricity', path: '/electricity', desc: 'Energy, power, and cost math.' },
      { name: 'BTU Calculator', path: '/btu', desc: 'Heat energy and HVAC requirements.' },
      { name: 'Temperature', path: '/temperature-converter', desc: 'C, F, and Kelvin conversions.' },
      { name: 'Frequency', path: '/frequency', desc: 'Wavelength and period math.' },
      { name: 'Dew Point', path: '/dew-point', desc: 'Calculate air moisture saturation.' },
      { name: 'Heat Index', path: '/heat-index', desc: 'Apparent temperature and humidity.' },
    ]
  },
  {
    title: 'Real Estate & Construction',
    slug: 'construction',
    description: 'Expert planning for property and projects. Estimate building materials or analyze the financial health of your real estate investments.',
    items: [
      { name: 'Mortgage Calculator', path: '/mortgage', desc: 'Primary mortgage payment analysis.' },
      { name: 'UK Mortgage', path: '/mortgage-uk', desc: 'Specific UK mortgage rules/taxes.' },
      { name: 'Canadian Mortgage', path: '/canadian-mortgage', desc: 'CA compounding and payment rules.' },
      { name: 'House Affordability', path: '/house-affordability', desc: 'Find your home budget range.' },
      { name: 'HELOC Calculator', path: '/heloc', desc: 'Home Equity Line of Credit.' },
      { name: 'Home Equity', path: '/home-equity', desc: 'Calculate property value minus debt.' },
      { name: 'Rent Calculator', path: '/rent', desc: 'Determine affordable monthly rent.' },
      { name: 'Rental Property', path: '/rental-property', desc: 'Analyze investment profit and ROI.' },
      { name: 'BRRRR Calculator', path: '/brrrr', desc: 'Buy, Rehab, Rent, Refi, Repeat strategy.' },
      { name: 'Concrete Calculator', path: '/concrete', desc: 'Estimate volume for building slabs.' },
      { name: 'Roofing Calculator', path: '/roofing', desc: 'Estimate shingles and materials.' },
      { name: 'Square Footage', path: '/square-footage', desc: 'Calculate floor and wall areas.' },
      { name: 'Paint Calculator', path: '/paint', desc: 'Estimate gallons and coverage.' },
      { name: 'Flooring Calculator', path: '/flooring', desc: 'Materials for wood, tile, carpet.' },
      { name: 'Tile Calculator', path: '/tile', desc: 'Estimate count and waste factors.' },
      { name: 'Fence Calculator', path: '/fence', desc: 'Posts, rails, and material costs.' },
      { name: 'Mulch Calculator', path: '/mulch', desc: 'Estimate volume for landscaping.' },
      { name: 'Gravel Calculator', path: '/gravel', desc: 'Tons and yards for driveways.' },
      { name: 'Stair Calculator', path: '/stair', desc: 'Rises, runs, and stringer lengths.' },
      { name: 'Wallpaper', path: '/wallpaper', desc: 'Analyze roll count and coverage.' },
      { name: 'Deck Calculator', path: '/deck', desc: 'Batten and joist material planning.' },
    ]
  },
  {
    title: 'Everyday Tools',
    slug: 'everyday',
    description: 'Utilities for the modern lifestyle. Secure your digital world, manage your time, or handle small mathematical tasks in your daily routine.',
    items: [
      { name: 'Time Calculator', path: '/time', desc: 'Durations and time additions.' },
      { name: 'Password Generator', path: '/password-generator', desc: 'Secure random credentials.' },
      { name: 'Word Counter', path: '/word-counter', desc: 'Count chars, words, reading time.' },
      { name: 'Hours Calculator', path: '/hours', desc: 'Daily and weekly work tracking.' },
      { name: 'Amazon FBA', path: '/amazon-fba', desc: 'E-commerce seller profit tools.' },
      { name: 'Percentage Off', path: '/percentage-off', desc: 'Quick holiday deal math.' },
      { name: 'Height Calculator', path: '/height', desc: 'Convert and predict stature.' },
      { name: 'Bra Size', path: '/bra-size', desc: 'Measure for comfort and support.' },
      { name: 'Dice Roller', path: '/dice-roller', desc: 'Virtual dice for tabletop games.' },
      { name: 'GDP Calculator', path: '/gdp', desc: 'Economic output analysis.' },
      { name: 'Tip Calculator', path: '/tip', desc: 'Split the bill and gratuity.' },
      { name: 'Discount Calculator', path: '/discount', desc: 'Retail savings and final prices.' },
      { name: 'IP Subnet', path: '/ip-subnet', desc: 'Network mask and address math.' },
    ]
  },
  {
    title: 'Automotive',
    slug: 'automotive',
    description: 'Keep your vehicle running efficiently. Manage fuel budgets, track depreciation, and analyze the true cost of car ownership.',
    items: [
      { name: 'MPG Calculator', path: '/mpg', desc: 'Calculate fuel efficiency trends.' },
      { name: 'Car Depreciation', path: '/car-depreciation', desc: 'Vehicle value loss over time.' },
      { name: 'Tire Size', path: '/tire-size', desc: 'Diameter and speedo adjustments.' },
      { name: 'Car Lease', path: '/car-lease', desc: 'Auto leasing payment breakdown.' },
      { name: 'Vehicle Tax', path: '/vehicle-tax', desc: 'Sales tax and registration costs.' },
      { name: 'Road Trip Cost', path: '/road-trip-cost', desc: 'Distance and fuel price planning.' },
      { name: 'Fuel Cost', path: '/fuel-cost', desc: 'Price per mile and trip totals.' },
      { name: 'Engine Horsepower', path: '/engine-horsepower', desc: 'Torque and RPM performance metrics.' },
    ]
  },
  {
    title: 'Insurance',
    slug: 'insurance',
    description: 'Secure your future with proper coverage. Our tools help you estimate how much life, health, or auto insurance you actually need.',
    items: [
      { name: 'Life Insurance', path: '/life-insurance', desc: 'Coverage for family protection.' },
      { name: 'Health Insurance', path: '/health-insurance', desc: 'Out-of-pocket and premium math.' },
      { name: 'Car Insurance', path: '/car-insurance', desc: 'Drive with financial peace of mind.' },
    ]
  },
  {
    title: 'Conversions',
    slug: 'conversions',
    description: 'Instant unit transformation. Convert length, weight, tech formats, and historical numbering systems with total accuracy.',
    items: [
      { name: 'Unit Converter', path: '/unit-converter', desc: 'Metric and Imperial conversions.' },
      { name: 'Currency Converter', path: '/currency-converter', desc: 'Live exchange rate calculations.' },
      { name: 'Roman Numerals', path: '/roman-numeral-converter', desc: 'Convert to and from Arabic numerals.' },
      { name: 'Hex Converter', path: '/hex', desc: 'Hex, Dec, and Bin conversions.' },
      { name: 'Binary Converter', path: '/binary', desc: 'Logic and base-2 math.' },
      { name: 'Base64 Converter', path: '/base64', desc: 'Encode and decode binary data.' },
      { name: 'URL Converter', path: '/url-converter', desc: 'Safe web address strings.' },
      { name: 'Shoe Size', path: '/shoe-size-conversion', desc: 'Global footwear standards.' },
      { name: 'Time Zone', path: '/time-zone-converter', desc: 'Global sync for meetings/travel.' },
      { name: 'Scientific Notation', path: '/scientific-notation', desc: 'Standard power-of-10 format.' },
    ]
  }
];
