import React from 'react';
import { 
  LineChart, 
  UserCircle, 
  ShieldCheck, 
  Sigma, 
  Home, 
  Building, 
  Hammer, 
  Droplets, 
  Square, 
  Paintbrush, 
  FlaskConical, 
  Calendar, 
  CarFront, 
  Activity, 
  Stethoscope, 
  Target, 
  ArrowLeftRight, 
  Briefcase, 
  Tags, 
  Wrench, 
  Timer, 
  Globe2, 
  Utensils, 
  BookOpen, 
  Gamepad, 
  Cpu, 
  Sun, 
  Dna, 
  Footprints, 
  Sprout, 
  Clock, 
  Globe, 
  Shirt, 
  Beaker, 
  Film, 
  Brain, 
  Gamepad2, 
  Baby, 
  Scale, 
  CircleDollarSign, 
  Monitor, 
  TrendingUp, 
  Truck, 
  Wifi, 
  Orbit, 
  Plane, 
  Compass,
  Calculator,
  Palette,
  Microscope,
  AudioLines,
  Map,
  Anchor,
  Siren,
  Database,
  CloudSun,
  Factory,
  Pill,
  Lock,
  Speaker,
  Package,
  Calculator as CalcIcon
} from 'lucide-react';

export const CATEGORY_ICON_MAP: Record<string, React.ReactNode> = {
  'finance': <LineChart />,
  'personal': <UserCircle />,
  'insurance': <ShieldCheck />,
  'math': <Sigma />,
  'roofing': <Home />,
  'real-estate': <Building />,
  'construction': <Hammer />,
  'hydraulics': <Droplets />,
  'masonry': <Square />,
  'home-improvement': <Paintbrush />,
  'science': <FlaskConical />,
  'everyday': <Calendar />,
  'automotive': <CarFront />,
  'health': <Activity />,
  'medical': <Stethoscope />,
  'military': <Target />,
  'converters': <ArrowLeftRight />,
  'business': <Briefcase />,
  'sales': <Tags />,
  'engineering': <Wrench />,
  'sports': <Timer />,
  'environment': <Globe2 />,
  'culinary': <Utensils />,
  'academic': <BookOpen />,
  'hobbies': <Gamepad />,
  'tech': <Cpu />,
  'lifestyle': <Sun />,
  'biology': <Dna />,
  'pets': <Footprints />,
  'gardening': <Sprout />,
  'time-date': <Clock />,
  'geography': <Globe />,
  'fashion': <Shirt />,
  'chemistry': <Beaker />,
  'entertainment': <Film />,
  'mental-health': <Brain />,
  'gaming': <Gamepad2 />,
  'parenting': <Baby />,
  'legal': <Scale />,
  'crypto': <CircleDollarSign />,
  'freelance': <Monitor />,
  'self-improvement': <TrendingUp />,
  'logistics': <Truck />,
  'home-tech': <Wifi />,
  'space': <Orbit />,
  'intl-travel': <Plane />,
  'survival-bushcraft': <Compass />,
  'creative-arts': <Palette />,
  'marine-science': <Anchor />,
  'data-science': <Database />,
  'cyber-sec': <Lock />,
  'geology': <Map />,
  'weather-pro': <CloudSun />,
  'retail-pro': <Package />,
  'manufacturing': <Factory />,
  'music-theory': <AudioLines />,
  'audio-pro': <Speaker />,
  'pharmacy': <Pill />,
  'disaster-prep': <Siren />,
  'pet-wellness': <Activity />
};

export const getCategoryIcon = (slug: string, className: string = "w-5 h-5") => {
  const icon = CATEGORY_ICON_MAP[slug] || <CalcIcon />;
  return React.cloneElement(icon as React.ReactElement<any>, { className });
};
